name: CI worker cargo

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    defaults:
      run:
        shell: bash
        working-directory: worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add packages folder to PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/packages" >> $GITHUB_ENV

      - name: Run worker tests
        run: |
          python -m unittest discover -vb -s tests
