name: CI worker msys2

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64,       comp: gcc }
    defaults:
      run:
        shell: msys2 {0}
        working-directory: worker

    steps:
      - name: Setup msys and install required packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.sys }}
          install: >-
            make
            mingw-w64-${{ matrix.env }}-python3
            mingw-w64-${{ matrix.env }}-${{ matrix.comp }}
            mingw-w64-x86_64-rust

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add packages folder to PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/packages" >> $GITHUB_ENV

      - name: Run worker tests
        run: |
          python -m unittest discover -vb -s tests